name: flutter_base
description: "Base classes, packages and components for any Flutter projects"
version: 1.0.0
homepage: https://github.com/channdara/flutter_base
issue_tracker: https://github.com/channdara/flutter_base/issues

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

scripts:
  test: 'flutter pub publish --dry-run'
  publish: 'flutter pub publish'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  dio: ^5.5.0+1
  intl: ^0.19.0
  collection: ^1.18.0
  flutter_bloc: ^8.1.6
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.2.3
  flutter_localization: ^0.2.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mastertipsy.flutter_base
        pluginClass: FlutterBasePlugin
      ios:
        pluginClass: FlutterBasePlugin
      linux:
        pluginClass: FlutterBasePlugin
      macos:
        pluginClass: FlutterBasePlugin
      windows:
        pluginClass: FlutterBasePluginCApi
      web:
        pluginClass: FlutterBaseWeb
        fileName: flutter_base_web.dart